// Every option below can also be used in a `sidebar.config.json` file, so
// adding or removing one here requires updating `OPTION_SPECS` in
// `config-file.ts`. The compiler reports it when the two go out of sync.
export declare interface VitePressSidebarOptions {
  documentRootPath?: string;
  scanStartPath?: string;
  resolvePath?: string;
  basePath?: string;
  collapsed?: boolean | null | undefined;
  collapseDepth?: number;
  collapseFromLevel?: number;
  hyphenToSpace?: boolean;
  underscoreToSpace?: boolean;
  capitalizeFirst?: boolean;
  capitalizeEachWords?: boolean;
  includeRootIndexFile?: boolean;
  includeFolderIndexFile?: boolean;
  useTitleFromFileHeading?: boolean;
  useTitleFromFrontmatter?: boolean;
  useFolderTitleFromIndexFile?: boolean;
  useFolderLinkFromIndexFile?: boolean;
  useFolderLinkFromSameNameSubFile?: boolean;
  includeDotFiles?: boolean;
  includeDynamicRoutes?: boolean;
  dynamicRouteTitleParam?: string;
  folderLinkNotIncludesFileName?: boolean;
  includeEmptyFolder?: boolean;
  sortMenusByName?: boolean;
  sortMenusByFileCreateDate?: boolean;
  sortMenusByFileModifyDate?: boolean;
  sortMenusByFrontmatterOrder?: boolean;
  sortMenusByFrontmatterDate?: boolean;
  sortMenusByFileDatePrefix?: boolean;
  sortMenusOrderByDescending?: boolean;
  sortMenusOrderNumericallyFromTitle?: boolean;
  sortMenusOrderNumericallyFromLink?: boolean;
  sortMenusByCustomFunction?: SidebarSortFunction;
  sortFolderTo?: null | undefined | 'top' | 'bottom';
  keepMarkdownSyntaxFromTitle?: boolean;
  debugPrint?: boolean;
  manualSortFileNameByPriority?: string[];
  excludeByFolderDepth?: number;
  excludeByGlobPattern?: string[];
  excludeFilesByFrontmatterFieldName?: string;
  followSymlinks?: boolean;
  removePrefixAfterOrdering?: boolean;
  prefixSeparator?: string | RegExp;
  rootGroupText?: string;
  rootGroupLink?: string;
  rootGroupCollapsed?: boolean | null | undefined;
  frontmatterOrderDefaultValue?: number;
  frontmatterTitleFieldName?: string;
  /**
   * @deprecated `excludePattern` has renamed `excludeByGlobPattern`. This option will be removed in a future version.
   */
  excludePattern?: string[];
}

// Every key below can be used under the `$folder` key of a
// `sidebar.config.json`, so adding or removing one here requires updating
// `FOLDER_META_SPECS` in `config-file.ts`. The compiler reports it when the
// two go out of sync.
export declare interface VitePressSidebarFolderMeta {
  order?: number;
  text?: string;
  link?: string;
}

export declare interface SidebarListItem {
  [key: string]: any;
}

/**
 * One side of a comparison made by `sortMenusByCustomFunction`.
 *
 * It describes where an item comes from on disk and not only how it is
 * displayed, so that an order can be decided from something the generator never
 * reads by itself, such as a date kept in version control.
 */
export declare interface SidebarSortItem {
  /** Text the item is displayed with. */
  text?: string;
  /** Link the item points to. Absent for a folder that has none. */
  link?: string;
  /** Name of the file or folder on disk, `.md` included. */
  fileName: string;
  /**
   * Absolute path of the file or folder on disk. For a page generated by a
   * dynamic route, the path of the template that generates it.
   */
  filePath: string;
  /** Whether the item is a folder. */
  isDirectory: boolean;
  /** Creation time in milliseconds, or `0` when it cannot be read. */
  createDate: number;
  /** Modification time in milliseconds, or `0` when it cannot be read. */
  modifyDate: number;
  /**
   * Frontmatter of the file, or of the `index.md` of a folder. An empty object
   * when there is none.
   */
  frontmatter: AnyValueObject;
}

/**
 * Compares two items the way `Array.prototype.sort` expects, and decides the
 * order of every level of the sidebar on its own.
 */
export declare type SidebarSortFunction = (a: SidebarSortItem, b: SidebarSortItem) => number;

export declare interface SortByObjectKeyOptions {
  arr: SidebarListItem;
  key: string;
  // Read instead of `key` from an item that does not carry it, so that an item
  // missing the key is still sorted against the others rather than being
  // compared as `undefined`.
  fallbackKey?: string;
  desc?: boolean;
  numerically?: boolean;
  datePrefixSeparator?: string | RegExp;
  dateSortFromFrontmatter?: boolean;
  dateSortFromTextWithPrefix?: boolean;
}

export declare type AnyValueObject = { [key: string]: any };

/*
 * Types from: `vitepress/types/default-theme.d.ts`
 */
export type SidebarItem = {
  text?: string;
  link?: string;
  items?: SidebarItem[];
  collapsed?: boolean;
};

export interface SidebarMultiItem {
  base: string;
  items: SidebarItem[];
}

export interface SidebarMulti {
  [path: string]: SidebarMultiItem;
}

export type Sidebar = SidebarItem[] | SidebarMulti;
/*
 * END
 */
